# Generated by Django 5.0.2 on 2024-03-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_alter_departamento_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['-name'], 'verbose_name': 'Mi Departamento', 'verbose_name_plural': 'Areas de las empresa'},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('name', 'short_name')},
        ),
    ]
