# Generated by Django 5.0.2 on 2024-03-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
